<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FinancialAccount;

class FinancialAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'account_code' => '1-100',
                'account_name' => 'Kas Resepsionis',
                'type' => 'asset',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Uang kembalian dan setoran tunak harian di meja front desk',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '1-120',
                'account_name' => 'Rekening Bank',
                'type' => 'asset',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Menampung uang transfer tamu dan penyelesaian dari transaksi cashless',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '1-210',
                'account_name' => 'Piutang OTA',
                'type' => 'asset',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Menampung tagihan kepada OTA (Online Travel Agent) yang belum dicairkan',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '1-220',
                'account_name' => 'Piutang Korporat',
                'type' => 'asset',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Tagihan kepada perusahaan atau instansi yang dibayar belakangan',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '1-310',
                'account_name' => 'Persediaan Barang(Inventory)',
                'type' => 'asset',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Nilai stok barang digudang seperti bahan makanan, minuman, alat kebersihan, amenity, sparepart kecil, dll',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '2-110',
                'account_name' => 'Uang Muka Tamu',
                'type' => 'liability',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Deposit atau uang muka yang diterima dari tamu sebelum menginap',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '2-120',
                'account_name' => 'Hutang Usaha',
                'type' => 'liability',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Tagihan jatuh tempo kepada supplier atau vendor yang belum dibayar',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '2-210',
                'account_name' => 'Hutang Pajak Hotel',
                'type' => 'liability',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Pajak yang wajib disetorkan pemerintah (PPH 21, PPN, PBJT) yang belum dibayar',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '3-110',
                'account_name' => 'Modal Pemilik',
                'type' => 'equity',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Uang atau aset yang disetorkan pertama kali oleh pemilik ke bisnis guesthouse',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '3-120',
                'account_name' => 'Laba Ditahan',
                'type' => 'equity',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Akumulasi laba bersih dari periode sebelumnya yang tidak dibagikan kepada pemilik',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '4-110',
                'account_name' => 'Pendapatan Kamar',
                'type' => 'revenue',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Pendapatan yang diperoleh dari penyewaan kamar',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '4-120',
                'account_name' => 'Pendapatan Additional',
                'type' => 'revenue',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Pendapatan yang diperoleh dari penyewaan additional',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '4-130',
                'account_name' => 'Pendapatan F&B',
                'type' => 'revenue',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Pendapatan yang diperoleh dari penjualan makanan dan minuman',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '4-140',
                'account_name' => 'Pendapatan Banquet',
                'type' => 'revenue',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Pendapatan yang diperoleh dari sewa ruang meeting, ballroom, dan paket acara',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '4-150',
                'account_name' => 'Pendapatan Lain-lain',
                'type' => 'revenue',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Denda late check-out, denda kamar, laundry tamu, atau ganti rugi barang rusak.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-110',
                'account_name' => 'Harga Pokok Penjualan (HPP) Makanan & Minuman',
                'type' => 'cost of goods sold',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya langsung pembelian bahan baku makanan dan minuman yang terjual',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-120',
                'account_name' => 'Biaya Gaji & Tunjangan',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Gaji pokok, lembur, tunjangan, dan bonus karyawan (front office, housekeeping, F&B, engineering, dll).',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-130',
                'account_name' => 'Biaya Pemasaran & Promosi',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya iklan online, commission OTA, marketing tools, dll.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-140',
                'account_name' => 'Biaya Utilitas & Pemeliharaan',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Tagihan listrik, air, gas, internet, telepon, serta biaya perawatan gedung, taman, kolam renang, dan perbaikan rutin.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-150',
                'account_name' => 'Biaya Operasional Kamar',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya linen, laundry tamu, amenity, sabun, shampoo, tisu, alat kebersihan, dan perlengkapan kamar lainnya.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-160',
                'account_name' => 'Biaya Umum & Administrasi',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya ATK, perlengkapan kantor, lisensi software, biaya bank, meterai, dan biaya operasional umum lainnya.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-170',
                'account_name' => 'Biaya Komisi OTA',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya komisi yang dibayarkan kepada Online Travel Agent (OTA) seperti Booking.com, Agoda, Traveloka, dll.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-180',
                'account_name' => 'Biaya Depresiasi Aset',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Penyusutan nilai gedung, furnitur, AC, TV, dan aset tetap lainnya dari waktu ke waktu.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-190',
                'account_name' => 'Biaya Penyusutan Aset',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Penyusutan nilai gedung, furnitur, AC, TV, dan aset tetap lainnya dari waktu ke waktu.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-200',
                'account_name' => 'Biaya Maintenance',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya maintenance yang dikeluarkan untuk memelihara dan memperbaiki fasilitas guesthouse.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'account_code' => '5-210',
                'account_name' => 'Biaya Lain-lain',
                'type' => 'expense',
                'balance' => 0,
                'is_active' => true,
                'description' => 'Biaya lain-lain yang tidak dapat diklasifikasikan ke dalam kategori di atas.',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];
    FinancialAccount::insert($data);
    }
}
