<?php
namespace Database\Seeders;

use App\Models\Menu;
use App\Models\RoleUserHasMenu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'code'        => 'DASHBOARD',
                'group_menu_id' => 1,
                'name'        => 'Dashboard',
                'icon'        => 'fe fe-grid',
                'url'         => '/dashboard',
                'have_list'   => 'Y',
                'have_create' => 'N',
                'have_edit'   => 'N',
                'have_delete' => 'N',
            ],
            [
                'code'        => 'MENU',
                'group_menu_id' => 2,
                'name'        => 'Menu',
                'icon'        => 'fe fe-grid',
                'url'         => '/menu',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'ROLE_USER',
                'group_menu_id' => 2,
                'name'        => 'Role User',
                'icon'        => 'fe fe-grid',
                'url'         => '/role',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'ROLE_AKSES',
                'group_menu_id' => 2,
                'name'        => 'Role Akses',
                'icon'        => 'fe fe-grid',
                'url'         => '/role-akses',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'DATA_USER',
                'group_menu_id' => 2,
                'name'        => 'Data User',
                'icon'        => 'fe fe-users',
                'url'         => '/user',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'ROOM_TYPE',
                'group_menu_id' => 3,
                'name'        => 'Tipe Kamar',
                'icon'        => 'fe fe-grid',
                'url'         => '/room-type',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'FACILITY',
                'group_menu_id' => 3,
                'name'        => 'Fasilitas',
                'icon'        => 'fe fe-grid',
                'url'         => '/facility',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            
            [
                'code'        => 'ADDITIONAL',
                'group_menu_id' => 2,
                'name'        => 'Layanan Tambahan',
                'icon'        => 'fe fe-grid',
                'url'         => '/additional',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'ROOM',
                'group_menu_id' => 3,
                'name'        => 'Kamar',
                'icon'        => 'fe fe-grid',
                'url'         => '/room',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'RESERVATION',
                'group_menu_id' => 4,
                'name'        => 'Reservasi',
                'icon'        => 'fe fe-grid',
                'url'         => '/reservations',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'BOOKING',
                'group_menu_id' => 4,
                'name'        => 'Pemesanan',
                'icon'        => 'fe fe-grid',
                'url'         => '/bookings',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'INVENTORY',
                'group_menu_id' => 5,
                'name'        => 'Inventaris',
                'icon'        => 'fe fe-grid',
                'url'         => '/inventory',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'TRACKING_INVENTORY',
                'group_menu_id' => 5,
                'name'        => 'Pelacakan Inventaris',
                'icon'        => 'fe fe-grid',
                'url'         => '/tracking-inventory',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'CASHFLOW',
                'group_menu_id' => 6,
                'name'        => 'Cash Flow',
                'icon'        => 'fe fe-grid',
                'url'         => '/cashflow',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'LEDGER',
                'group_menu_id' => 6,
                'name'        => 'Ledger',
                'icon'        => 'fe fe-grid',
                'url'         => '/ledger',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'FINANCIAL_REPORT',
                'group_menu_id' => 6,
                'name'        => 'Laporan Keuangan',
                'icon'        => 'fe fe-grid',
                'url'         => '/financial-report',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'GUEST_REPORT',
                'group_menu_id' => 4,
                'name'        => 'Tamu',
                'icon'        => 'fe fe-grid',
                'url'         => '/guest-report',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code'        => 'HOUSEKEEPING',
                'group_menu_id' => 4,
                'name'        => 'Housekeeping',
                'icon'        => 'fe fe-grid',
                'url'         => '/housekeeping',
                'have_list'   => 'Y',
                'have_create' => 'Y',
                'have_edit'   => 'Y',
                'have_delete' => 'Y',
            ],
            [
                'code' => 'EMPLOYEE',
                'group_menu_id' => 2,
                'name' => 'Karyawan',
                'icon' => 'fe fe-grid',
                'url' => '/employee',
                'have_list' => 'Y',
                'have_create' => 'Y',
                'have_edit' => 'Y',
                'have_delete' => 'Y',
            ],
        ];
        foreach ($data as $item) {
            $menu = Menu::create($item);
            RoleUserHasMenu::create([
                'id_role'       => 1,
                'id_menu'       => $menu->id,
                'access_list'   => $item['have_list'],
                'access_create' => $item['have_create'],
                'access_edit'   => $item['have_edit'],
                'access_delete' => $item['have_delete'],
            ]);

        }
    }
}
